context:
  version: "0.8.0"

package:
  name: simple-http-server
  version: ${{ version }}

source:
  url: https://github.com/TheWaWaR/simple-http-server/archive/refs/tags/v${{ version }}.tar.gz
  sha256: b60965e0b0cd652bcb734185e6d8395cd4c1326305b190cba6ba0d7819f38af2

build:
  number: 1
  script:
    env:
      CARGO_PROFILE_RELEASE_LTO: fat
      CARGO_PROFILE_RELEASE_STRIP: symbols
      OPENSSL_NO_VENDOR: "1" # force linking to host's (conda-forge's) OpenSSL libs
      # instruct `cc` crate to use clang-cl natively to compile build-time tools intended to be run on the host when cross-compiling from `win_64`
      # (fixes compilation of `libopenssl_sys`)
      AR_x86_64_pc_windows_msvc: llvm-lib
      CC_x86_64_pc_windows_msvc: clang-cl
      CXX_x86_64_pc_windows_msvc: clang-cl
    content:
      - if: unix
        then:
          - cargo auditable install --path=. --root="$PREFIX" --no-track --locked --bins --features=tls
      - if: win
        then:
          - set "OPENSSL_DIR=%LIBRARY_PREFIX%"
          - cargo auditable install --path=. --root="%LIBRARY_PREFIX%" --no-track --locked --bins --features=tls
      - cargo-bundle-licenses --format=yaml --output=./THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-auditable
    - cargo-bundle-licenses
    - if: unix
      then: pkg-config
  host:
    - openssl

tests:
  - script:
      - simple-http-server --help
      - simple-http-server --version
  - package_contents:
      bin:
        - simple-http-server
      strict: true

about:
  summary: Simple HTTP server in Rust
  description: |
    A simple HTTP(S) server for static files, written in Rust. Supports directory listing, upload, basic auth, range requests, compression, CORS, SPA fallback,
    and PKCS #12 files.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://github.com/TheWaWaR/simple-http-server
  repository: https://github.com/TheWaWaR/simple-http-server

extra:
  recipe-maintainers:
    - salim-b
